name: ios-framework

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master  
    - name: Build iOS framework
      run: ./packages/build_ios.sh
    - uses: actions/upload-artifact@v4
      with:
        name: KataGo-iOS-OS64COMBINED.zip
        path: ./packages/build/Release-universal/KataGo-iOS-OS64COMBINED.zip
